#
# This file was generated by the ./configure script.
# Generated on: Thu Jul 24 17:23:19 KST 2025
# Configuration:
#   Compiler: pgi
#   Debug: no
#   Defines: -DNMEG=400000L 
#

AR = ar rcv
RANLIB = ranlib

# PGI Compiler Settings
OPT = -O3  -qopenmp -DINDEX -DVarPM -DXYZDBL -DNENER=0 -DNPRE=8 -DREAD_SINK -DNCHEM=9 -DNDUST=4 -DADV
DFLAGS = -DNMEG=400000L  -D_LARGE_FILES
FFLAGS = $(DFLAGS) $(OPT) -mcmodel=medium
CFLAGS = $(DFLAGS) $(OPT) -mcmodel=medium
LDFLAGS = $(OPT) -mcmodel=medium
LIBS = -lm
CC = mpicc
FC = mpifort

#--- Compilation Rules ---
.SUFFIXES: .exe .o .c .f .F

.c.o:
	$(CC) $(CFLAGS) $(INCLUDES) -c $<

.f.o:
	$(FC) $(FFLAGS) $(INCLUDES) -c $<

.F.o:
	$(FC) $(FFLAGS) $(INCLUDES) -c $<

.f.exe:
	$(FC) $(LDFLAGS) $(INCLUDES) -o $*.exe $(OBJS) $(MPI_LINKS) $(LIBS)

.c.exe:
	$(CC) $(LDFLAGS) $(INCLUDES) -o $*.exe $(OBJS) $(MPI_LINKS) $(LIBS)
